### ISSUE TITLE
[Roadmap] Next (major) release

### ISSUE THREAD

**Issue by chmp** [chmp/serde_arrow#61]
Planned features:

- [x] #65 
- [x] #60
- [x] #43
- [x] #51 
- [x] #53
- [x] #38 
- [x] #62 
- [x] #54
- [x] #56

Skip for now:

- [x] #44

Misc:

- [x] Document the meaning of the schema: the schema describes the arrays not the rust structs
- [x] Re-implement maps for the outer struct (tests: `test_maps_with_missing_items`, `into_outer_maps_simple`)
- [x] Test Lists with i32 offsets
- [x] Remove special cased dictionaries in interpreter and use raw buffers directly
- [x] ~~Test different order between arrrays and fields~~ (cannot happen: the order of arrays and fields must be consistent)

**Comment by chmp** [comment]
Release v0.8.0-rc.1
