### ISSUE TITLE
Release 0.9.0

### ISSUE THREAD

**Issue by chmp** [chmp/serde_arrow#95]
- [x] #100
- [x] #94 
- [x] Add arrow=49 support (implemented via #102)
- [x] Automate arrow updates (implemented via #102)
- [x] #92  -- postpone to a later release. Initial tests did not show a performance improvement
